// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Location.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Location TABLE
class TableLocation extends SqfEntityTableBase {
  TableLocation() {
    // declare properties of EntityTable
    tableName = 'location';
    relationType = null;
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('data', DbType.text),
      SqfEntityFieldBase('datetime', DbType.datetime),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableLocation();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    databaseTables = [
      TableLocation.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Location
class Location {
  Location({this.id, this.data, this.datetime, this.isDeleted}) {
    _setDefaultValues();
  }
  Location.withFields(this.data, this.datetime, this.isDeleted) {
    _setDefaultValues();
  }
  Location.withId(id, this.data, this.datetime, this.isDeleted) {
    _setDefaultValues();
  }
  Location.fromMap(Map<String, dynamic> o) {
    _setDefaultValues();
    id = int.tryParse(o['id'].toString());
    if (o['data'] != null) data = o['data'] as String;
    if (o['datetime'] != null)
      datetime = int.tryParse(o['datetime'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['datetime'].toString()))
          : DateTime.tryParse(o['datetime'].toString());
    isDeleted = o['isDeleted'] != null
        ? o['isDeleted'] == 1 || o['isDeleted'] == true
        : null;
  }
  // FIELDS (Location)
  int id;
  String data;
  DateTime datetime;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Location)

  static const bool _softDeleteActivated = true;
  LocationManager __mnLocation;

  LocationManager get _mnLocation {
    return __mnLocation = __mnLocation ?? LocationManager();
  }

  // METHODS
  Map<String, dynamic> toMap({bool forQuery = false, bool forJson = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (data != null) {
      map['data'] = data;
    }

    if (datetime != null) {
      map['datetime'] = forJson
          ? datetime.toString()
          : forQuery ? datetime.millisecondsSinceEpoch : datetime;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChilds(
      [bool forQuery = false, bool forJson = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (data != null) {
      map['data'] = data;
    }

    if (datetime != null) {
      map['datetime'] = forJson
          ? datetime.toString()
          : forQuery ? datetime.millisecondsSinceEpoch : datetime;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method always returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method always returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChilds(false, true));
  }

  List<dynamic> toArgs() {
    return [
      data,
      datetime != null ? datetime.millisecondsSinceEpoch : null,
      isDeleted
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      data,
      datetime != null ? datetime.millisecondsSinceEpoch : null,
      isDeleted
    ];
  }

  static Future<List<Location>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print(
          'SQFENTITY ERROR Location.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Location>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Location>[];
    try {
      objList = list
          .map((location) => Location.fromMap(location as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Location.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  /*
    /// REMOVED AFTER v1.2.1+14 
    static Future<List<Location>> fromObjectList(Future<List<dynamic>> o) async {
      final data = await o;
      return await Location.fromMapList(data);
    } 
    */

  static Future<List<Location>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false}) async {
    final List<Location> objList = <Location>[];
    for (final map in data) {
      final obj = Location.fromMap(map as Map<String, dynamic>);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Location by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Location if exist, otherwise returns null
  Future<Location> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false}) async {
    if (id == null) {
      return null;
    }
    Location obj;
    final data = await _mnLocation.getById([id]);
    if (data.length != 0) {
      obj = Location.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Location) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnLocation.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnLocation.update(this);
    }

    return id;
  }

  /// saveAs Location. Returns a new Primary Key value of Location

  /// <returns>Returns a new Primary Key value of Location
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Location> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  Future<List<dynamic>> saveAll(List<Location> locations) async {
    // final results = _mnLocation.saveAll('INSERT OR REPLACE INTO location (id,data, datetime,isDeleted)  VALUES (?,?,?,?)',locations);
    // return results; removed in sqfentity_gen 1.3.0+6
    MyDbModel().batchStart();
    for (final obj in locations) {
      await obj.save();
    }
    return MyDbModel().batchCommit();
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnLocation.rawInsert(
              'INSERT OR REPLACE INTO location (id,data, datetime,isDeleted)  VALUES (?,?,?,?)',
              [
                id,
                data,
                datetime != null ? datetime.millisecondsSinceEpoch : null,
                isDeleted
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Location id=$id updated successfuly');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Location id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Location Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Location>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a <List<BoolResult>>
  Future<List<BoolResult>> upsertAll(List<Location> locations) async {
    final results = await _mnLocation.rawInsertAll(
        'INSERT OR REPLACE INTO location (id,data, datetime,isDeleted)  VALUES (?,?,?,?)',
        locations);
    return results;
  }

  /// Deletes Location

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Location invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnLocation
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnLocation.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Location>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Location invoked (id=$id)');
    {
      return _mnLocation.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  //private LocationFilterBuilder _Select;
  LocationFilterBuilder select(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return LocationFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  LocationFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return LocationFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion location

// region LocationField
class LocationField extends SearchCriteria {
  LocationField(this.locationFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  LocationFilterBuilder locationFB;

  LocationField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  LocationFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param, SqlSyntax.EQuals,
            locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param, SqlSyntax.NotEQuals,
            locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.EQualsOrNull, locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder isNull() {
    locationFB._addedBlocks = setCriteria(
        0,
        locationFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      locationFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          locationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          locationFB._addedBlocks);
      _waitingNot = '';
      locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
          locationFB._addedBlocks.retVal;
    }
    return locationFB;
  }

  LocationFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      locationFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          locationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          locationFB._addedBlocks);
      _waitingNot = '';
      locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
          locationFB._addedBlocks.retVal;
      locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
          locationFB._addedBlocks.retVal;
    }
    return locationFB;
  }

  LocationFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      locationFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          locationFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          locationFB._addedBlocks);
      _waitingNot = '';
      locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
          locationFB._addedBlocks.retVal;
    }
    return locationFB;
  }

  LocationFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      locationFB._addedBlocks = setCriteria(
          pFirst,
          locationFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          locationFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        locationFB._addedBlocks = setCriteria(pFirst, locationFB.parameters,
            param, SqlSyntax.LessThan, locationFB._addedBlocks);
      } else {
        locationFB._addedBlocks = setCriteria(pFirst, locationFB.parameters,
            param, SqlSyntax.GreaterThanOrEquals, locationFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        locationFB._addedBlocks = setCriteria(pLast, locationFB.parameters,
            param, SqlSyntax.GreaterThan, locationFB._addedBlocks);
      } else {
        locationFB._addedBlocks = setCriteria(pLast, locationFB.parameters,
            param, SqlSyntax.LessThanOrEquals, locationFB._addedBlocks);
      }
    }
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.GreaterThan, locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.LessThanOrEquals, locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param, SqlSyntax.LessThan,
            locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param, SqlSyntax.LessThan,
            locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    locationFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.LessThanOrEquals, locationFB._addedBlocks)
        : setCriteria(pValue, locationFB.parameters, param,
            SqlSyntax.GreaterThan, locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }

  LocationFilterBuilder inValues(dynamic pValue) {
    locationFB._addedBlocks = setCriteria(
        pValue,
        locationFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        locationFB._addedBlocks);
    _waitingNot = '';
    locationFB._addedBlocks.needEndBlock[locationFB._blockIndex] =
        locationFB._addedBlocks.retVal;
    return locationFB;
  }
}
// endregion LocationField

// region LocationFilterBuilder
class LocationFilterBuilder extends SearchCriteria {
  LocationFilterBuilder(Location obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Location _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  LocationFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  LocationFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  LocationFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  LocationFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter();
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  LocationFilterBuilder page(int page, int pagesize) {
    if (page > 0) _page = page;
    if (pagesize > 0) _pagesize = pagesize;
    return this;
  }

  /// int count = LIMIT
  LocationFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  LocationFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  LocationFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  LocationFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s desc ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  LocationFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') groupByList.add(' $s ');
        }
      }
    }
    return this;
  }

  LocationField setField(LocationField field, String colName, DbType dbtype) {
    return LocationField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  LocationField _id;
  LocationField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  LocationField _data;
  LocationField get data {
    return _data = setField(_data, 'data', DbType.text);
  }

  LocationField _datetime;
  LocationField get datetime {
    return _datetime = setField(_datetime, 'datetime', DbType.datetime);
  }

  LocationField _isDeleted;
  LocationField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Location._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Location> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();
    if (Location._softDeleteActivated && !hardDelete) {
      r = await _obj._mnLocation.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnLocation.delete(qparams);
    }
    return r;
  }

  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Location bulk invoked');
    return _obj._mnLocation.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from location ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnLocation.updateBatch(qparams, values);
  }

  /// This method always returns Location Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Location>
  Future<Location> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnLocation.toList(qparams);
    final data = await objFuture;
    Location obj;
    if (data.isNotEmpty) {
      obj = Location.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) locationCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final locationsFuture = await _obj._mnLocation.toList(qparams);
    final int count = locationsFuture[0]['CNT'] as int;
    if (locationCount != null) {
      locationCount(count);
    }
    return count;
  }

  /// This method always returns List<Location>.
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Location>
  Future<List<Location>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false}) async {
    final data = await toMapList();
    final List<Location> locationsData = await Location.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents);
    return locationsData;
  }

  /// This method always returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method always returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChilds(false, true));
    }
    return json.encode(list);
  }

  /// This method always returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnLocation.toList(qparams);
  }

  /// Returns List<DropdownMenuItem<Location>>
  Future<List<DropdownMenuItem<Location>>> toDropDownMenu(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<Location>> o)
          dropDownMenu]) async {
    _buildParameters();
    final locationsFuture = _obj._mnLocation.toList(qparams);

    final data = await locationsFuture;
    final int count = data.length;
    final List<DropdownMenuItem<Location>> items = []..add(DropdownMenuItem(
        value: Location(),
        child: Text('Select Location'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: Location.fromMap(data[i] as Map<String, dynamic>),
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// Returns List<DropdownMenuItem<int>>
  Future<List<DropdownMenuItem<int>>> toDropDownMenuInt(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<int>> o)
          dropDownMenu]) async {
    _buildParameters();
    qparams.selectColumns = ['id', displayTextColumn];
    final locationsFuture = _obj._mnLocation.toList(qparams);

    final data = await locationsFuture;
    final int count = data.length;
    final List<DropdownMenuItem<int>> items = []..add(DropdownMenuItem(
        value: 0,
        child: Text('Select Location'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: data[i]['id'] as int,
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// This method always returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) _buildParameters();
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnLocation.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject(
      [VoidCallback Function(List<dynamic> o) listObject]) async {
    _buildParameters();

    final objectFuture = _obj._mnLocation.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    if (listObject != null) {
      listObject(objectsData);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Location.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnLocation.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion LocationFilterBuilder

// region LocationFields
class LocationFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fData;
  static TableField get data {
    return _fData = _fData ?? SqlSyntax.setField(_fData, 'data', DbType.text);
  }

  static TableField _fDatetime;
  static TableField get datetime {
    return _fDatetime = _fDatetime ??
        SqlSyntax.setField(_fDatetime, 'datetime', DbType.datetime);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion LocationFields

//region LocationManager
class LocationManager extends SqfEntityProvider {
  LocationManager()
      : super(MyDbModel(),
            tableName: _tableName, // colId: _colId,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static String _tableName = 'location';
  //static String _colId = 'id';
  static List<String> _primaryKeyList = ['id'];
  static String _whereStr = 'id=?';
}

//endregion LocationManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
